version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dbaccenture?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678

  db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: dbaccenture
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678